### ISSUE TITLE
Comments from the Twitter verse

### ISSUE THREAD

**Issue by AJHalford** [kylermurphy/gmag#2]
From Eelco Doornbos "Installation instructions could be made more clear though. I can't get it to work using pipenv. There's probably a straightforward answer, but I'm not sure where I must put that gmagrc file. The error on importing gmag, when this file is not found is also not very clear at first. 

" now  got it to work by modifying and copying gmagrc_example to ~/gmagrc/gmagrc. Locations in the instructions in the code comments (~/.magpy/gmagrc) and example file (~/.gmag/gmagrc with extra dot) were both wrong. 🤪"

I think this is just a path issue.

**Comment by kylermurphy** [comment]
The module has not been tested with the pipenv package at this time.
